### PR TITLE
Rule error as a function

### PR DESCRIPTION
**Pull request by Nevoss**
Adding the option to set Rule error message as a function
related issue: #43.
also, add ".idea" to .gitignore.

Let me know if there is something to fix.

### CODE REVIEW

**Comment by oussamahamdaoui** [comment]
Hey, what i was trying to say is that if i have this case:
```javascript
const vComplexe = new Validator({
    age: new Rule({
      type: 'int', min: 18, max: 99,
    }, 'age must be integer and between 18 and 99'),
    dateOfBirth: new Rule({ type: 'date' }, 'date must be a date'),
    name: new Rule({ type: 'string', minLength: 2, }, (key, value) => `${key} must be a string, ${value} is not a string`),
  });
vComplexe.getErrors({
    age: 16,
    dateOfBirth: new Date(),
    name: 'a',
  });  // ['age must be integer and between 18 and 99', 'name must be a string, a is not a string'] 

// I susspect that you will get this error wich is not a good behaviour
```
Thats what i was trying to explain , im trying to think of a good way to manage errors inside of a rule
By the way im glad that you understood the code so fast hope that you didnt see to many wierd stuff 😬

**Comment by Nevoss** [comment]
First, do you prefer to make the discussion here or in the issue?
then I think there are 2 problems here from what I see.

1. you cannot know from the output error which error is belong to which key
2. then we need to find some way to send a message related to specific "Rule property"

So the solution for the first one is very clear the errors array will become an error object that will be like this:
```JS
{
  age: ['age must be integer and between 18 and 99'],
  name: ['name must be a string, a is not a string']
}
// as you can see the value of each property is an array, I set it as a preparation for the next answer.
```
but this is a breaking change so I guess you need to think about it.


The second solution is maybe to give the user the option to set for each `Rule` property an error message as well, maybe like this one:
```JS
const vComplexe = new Validator({
    age: new Rule({
      type: 'int',  // will have default error message
      min: {
        value: 18,
        message: 'age must be greater then 18'
      }, 
      max: {
        value: 99,
        message: 'age must be lower than 99'
      },
    }, 'age is not valid' // The default error message),
});
```
of course, this is a very big change and maybe too complex to use and implements.
and this is only my idea maybe other people have better ideas.

let me know if you need help with that, I really think that this library is great 👍 

by the way, the code was very clean (maybe a "prettier" or something will help keep it clean)

**Comment by Nevoss** [comment]
Hey, I just push some implementation idea, please check this out and if this seems a good idea, I will make it a little bit structure and write some tests.
also, I will love to hear about some improvements to the code.

**Comment by oussamahamdaoui** [comment]
Looks good, thats exeactly what i wanted to do, I didnt make a hole new class for error handling but this looks really good. Thank you.

**Comment by Nevoss** [comment]
Great I will test it and restructuring it a little bit.

**Comment by oussamahamdaoui** [comment]
Thank you tell me if a can help

**Comment by Nevoss** [comment]
Hey, just update my brach, it seems like there is no coverage report any more here in git hub, but the tests are 100% coverage again.

**Pull request merged**
